server:
     port: 9090
spring:
  datasource:
    source :
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//10.21.2.204:1521/ORCL
      username: JKPTCFOLD
      password: DESIGNER
    target:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//10.21.2.204:1521/ORCL
      username: JKPTCF
      password: DESIGNER